### ISSUE TITLE
Crash at Start

### ISSUE THREAD

**Issue by gabeernie** [SpitefulFox/SchoolsofMagic#2]
Attempting to launch the game with this mod results in a crash.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  ThaumcraftLoader (Thaumcraft-1.8.9-5.2.4.jar)
  thaumicinfusion (ThaumicInfusion-1.8.9-4.85.jar)
  LoadingPlugin (Bloodmoon-MC1.8.8-1.4.jar)
  LoadingPlugin (ChunkAnimator-MC1.8.8-1.1.jar)
Contact their authors BEFORE contacting forge

// I bet Cylons wouldn't have this problem.

Time: 7/5/16 8:00 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: fox/spiteful/schoolsmagic/items/ItemExtraColorizer
    at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:162)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:559)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:417)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: fox/spiteful/schoolsmagic/items/ItemExtraColorizer
    at fox.spiteful.schoolsmagic.Magic.bell(Magic.java:46)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:560)
    at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:211)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:189)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:556)
    ... 10 more
Caused by: java.lang.ClassNotFoundException: fox.spiteful.schoolsmagic.items.ItemExtraColorizer
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 37 more
Caused by: java.lang.NoClassDefFoundError: vazkii/psi/api/cad/ICADColorizer
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(Unknown Source)
    at java.security.SecureClassLoader.defineClass(Unknown Source)
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
    ... 39 more
Caused by: java.lang.ClassNotFoundException: vazkii.psi.api.cad.ICADColorizer
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 43 more
Caused by: java.lang.NullPointerException
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
    ... 45 more
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.8.9
    Operating System: Windows 7 (amd64) version 6.1
    CPU: 4x Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz
    Java Version: 1.8.0_91, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 709987736 bytes (677 MB) / 1060372480 bytes (1011 MB) up to 2134114304 bytes (2035 MB)
    JVM Flags: 7 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M -Xms1G
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP 9.19 Powered by Forge 11.15.1.1764 Optifine OptiFine_1.8.9_HD_U_H2 29 mods loaded, 29 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCH mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
    UCH FML{8.0.99.99} [Forge Mod Loader](forge-1.8.9-11.15.1.1764.jar) 
    UCH Forge{11.15.1.1764} [Minecraft Forge](forge-1.8.9-11.15.1.1764.jar) 
    UCH cei{0.1} [Chunk Edge Indicator](1.8.9-chunkedgeindicator-1.0.jar) 
    UCH ArchitectureCraft{1.4.1} [ArchitectureCraft](ArchitectureCraft-1.4.1-mc1.8.9.jar) 
    UCH Baubles{1.1.3.0} [Baubles](Baubles-1.8.9-1.1.3.0.jar) 
    UCH Thaumcraft{5.2.4} [Thaumcraft](Thaumcraft-1.8.9-5.2.4.jar) 
    UCH Automagy{2.0.3} [Automagy](Automagy-1.8.9-2.0.3.jar) 
    UCH bigtrees{0.2} [The BigTrees Mod](bigtrees-0.2-1.8.9.jar) 
    UCH BiomesOPlenty{3.0.0} [Biomes O' Plenty](BiomesOPlenty-1.8.9-3.0.0.1620-universal.jar) 
    UCH Bloodmoon{1.2} [Bloodmoon](Bloodmoon-MC1.8.8-1.4.jar) 
    UCH Botania{r1.8-299} [Botania](Botania-unofficial.r1.8-299.jar) 
    UCH ChunkAnimator{1.1} [Chunk Animator](ChunkAnimator-MC1.8.8-1.1.jar) 
    UCH ftfloocraft{1.8.9-0.2} [Floocraft](Floocraft-1.8.9-0.2.jar) 
    UCH foragecraft{1.1} [ForageCraft](ForageCraft-1.1.jar) 
    UCH hammerz{1.8.9-0.1.5.18} [Hammerz](Hammerz-1.8.9-0.1.5.18.jar) 
    UCH ImmersiveEngineering{0.8-26} [Immersive Engineering](ImmersiveEngineering-0.8-26.jar) 
    UCH JEI{2.22.3.105} [Just Enough Items](jei_1.8.9-2.22.3.105.jar) 
    UCH JEIAddons{0.10.0.35} [Just Enough Items Addons](JEIAddons_1.8.9-0.10.0.35.jar) 
    UCH journeymap{5.1.3} [JourneyMap](journeymap-1.8.8-5.1.3-unlimited.jar) 
    UCH jeresources{0.2.1.@BUILD@} [Just Enough Resources](JustEnoughResources-1.8.9-0.2.1.jar) 
    UCH parachutemod{1.2.2} [Parachute Mod](parachutemod-ng-1.8.9-1.2.2-341.jar) 
    UCH PetBat{1.4.0} [Pet Bat](PetBat-1.8.8.jar) 
    UCH ProjectE{1.8.9-PE1.1.4} [ProjectE](ProjectE-1.8.9-PE1.1.4.jar) 
    UCH Roguelike{1.5.0} [Roguelike Dungeons](RoguelikeDungeons-1.8.9-1.5.0.jar) 
    UCE SchoolsMagic{1.0} [Schools of Magic](SchoolsMagic-1.8.9-1.0.jar) 
    UCH thaumicinfusion{4.85} [Thaumic Infusion](ThaumicInfusion-1.8.9-4.85.jar) 
    UCH Torcherino{@VERSION@} [Torcherino](Torcherino-TehNut-1.8.9-2.2s.jar) 
    UCH villagebox{0.3.0 beta} [Village Box](villagebox-beta 0.3.0.jar) 
    Loaded coremods (and transformers): 
ThaumcraftLoader (Thaumcraft-1.8.9-5.2.4.jar)

thaumicinfusion (ThaumicInfusion-1.8.9-4.85.jar)
  drunkmafia.thaumicinfusion.common.asm.BlockTransformer
  drunkmafia.thaumicinfusion.common.asm.WorldTransformer
LoadingPlugin (Bloodmoon-MC1.8.8-1.4.jar)
  lumien.bloodmoon.asm.ClassTransformer
LoadingPlugin (ChunkAnimator-MC1.8.8-1.1.jar)
  lumien.chunkanimator.asm.ClassTransformer
    GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 368.22' Renderer: 'GeForce GTX 770/PCIe/SSE2'

**Comment by SpitefulFox** [comment]
Thanks for the crash report.  A new version of the mod has been uploaded that should fix the bug.
